config/routes.rb
Rails.application.routes.draw do
  root to: 'static#index'
  get :favicon, to: 'static#favicon'
  get :mvests, to: 'static#mvests'

  resources :static, only: :index
  resources :discussions, only: :index do
    collection do
      get :card
    end
  end
  resources :blocks, only: :index
  resources :follows, only: :index
  resources :accounts, only: :index
  resources :transfers, only: :index
  resources :tickers, param: :pair, only: [:index, :show]
  resources :charts, param: :account_name, only: [:index, :show] do
    member do
      get :net_transfers
      get :day_of_the_week
    end
  end

  get 'chart/accounts_created', to: 'charts#accounts_created'
  get 'chart/accounts_last_bandwidth_updated', to: 'charts#accounts_last_bandwidth_updated'
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  def index
    @other_promoted = params[:other_promoted].presence || 'false'
    @predicted = params[:predicted].presence || 'false'
    @trending_flagged = params[:trending_flagged].presence || 'false'
    @trending_by_reputation = params[:trending_by_reputation].presence || 'false'
    @trending_ignored = params[:trending_ignored].presence || 'false'
    @trending_by_rshares = params[:trending_by_rshares].presence || 'false'
    @vote_ready = params[:vote_ready].presence || 'false'
    @flagwar = params[:flagwar].presence || 'false'
    @first_post = params[:first_post].presence || 'false'
    @mentions = params[:mentions].presence || 'false'
    @limit = params[:limit].presence || '100'
    @tag = params[:tag].presence || nil
    @exclude_tags = params[:exclude_tags].presence || ''
    @max_votes = (params[:max_votes].presence || '10').to_i
    @min_age_in_minutes = (params[:min_age_in_minutes].presence || '30').to_i
    @min_reputation = (params[:min_reputation].presence || '25').to_i
    @max_reputation = (params[:max_reputation].presence || '99').to_i
    @min_promotion_amount = (params[:min_promotion_amount].presence || '0.001').to_f
    @min_rshares = (params[:min_rshares].presence || '25000000000000').to_i
    @max_rshares = (params[:max_rshares].presence || '99999999999999').to_i
    @flagged_by = params[:flagged_by].presence || ''
    @order_by = params[:order_by].presence || ''

    @discussions = comments.none
    
    other_promoted if @other_promoted == 'true'
    predicted if @predicted == 'true'
    trending_flagged if @trending_flagged == 'true'
    trending_by_reputation if @trending_by_reputation == 'true'
    trending_ignored if @trending_ignored == 'true'
    trending_by_rshares if @trending_by_rshares == 'true'
    vote_ready if @vote_ready == 'true'
    flagwar if @flagwar == 'true'
    first_post if @first_post == 'true'
    mentions if @mentions == 'true'
  end
  
  def card
    index
  end
private
  def other_promoted
    @limit = @limit.to_i

    response = api_execute(:get_account_history, 'null', -@limit, @limit)
    history = response.result

    @discussions += history.map do |entry|
      next unless entry.last.op.first == 'transfer'
      
      timestamp = Time.parse(entry.last.timestamp + 'Z')
      op = entry.last.op.last
      from = op.from
      memo = op.memo
      amount = op.amount
      base_amount = amount.split(' ').first.to_f
      
      next if base_amount < @min_promotion_amount
      next if memo.nil? || memo.empty?
      next if memo.include? from

      slug = memo.split('@').last
      author, url = slug.split('/')
      
      {
        slug: slug,
        url: "/tag/@#{slug}",
        from: from,
        amount: amount,
        timestamp: timestamp,
        votes: nil,
        title: memo,
        content: '',
        author: author
      }
    end.reject(&:nil?)
    
    accounts = @discussions.map do |discussion|
      [discussion[:author], discussion[:from]]
    end.flatten.uniq
    
    if accounts.any?
      accounts = api_execute(:get_accounts, accounts).result
      
      @discussions.each do |discussion|
        accounts.each do |account|
          if discussion[:author] == account.name
            discussion[:author_reputation] = to_rep(account.reputation)
          end
          
          if discussion[:from] == account.name
            discussion[:from_reputation] = to_rep(account.reputation)
          end
        end
      end
    end
    
    render_discussions(:other_promoted)
  end
  
  def predicted
    @discussions = discussions(with: FindPredictedJob, tag: @tag)
    
    render_discussions(:predicted)
  end
  
  def trending_by_reputation
    response = api_execute(:get_discussions_by_trending, limit: 100)
    
    @discussions += response.result.map do |comment|
      next if (author_reputation = to_rep(comment.author_reputation)) > @max_reputation
      next if author_reputation < @min_reputation
      
      {
        symbol: symbol_value(comment.total_pending_payout_value),
        url: comment.url,
        slug: comment.url.split('@').last,
        timestamp: comment.cashout_time,
        votes: comment.active_votes.size,
        title: comment.title,
        content: comment.body,
        author: comment.author,
        author_reputation: author_reputation
      }
    end.reject(&:nil?)
    
    render_discussions(:trending_by_reputation)
  end
  
  def trending_by_rshares
    response = api_execute(:get_discussions_by_trending, limit: 100)
    
    @discussions += response.result.map do |comment|
      next if (max_rshares = comment.active_votes.map(&:rshares).map(&:to_i).max) > @max_rshares
      next if max_rshares < @min_rshares
      
      {
        symbol: symbol_value(comment.total_pending_payout_value),
        url: comment.url,
        slug: comment.url.split('@').last,
        timestamp: comment.cashout_time,
        votes: comment.active_votes.size,
        title: comment.title,
        content: comment.body,
        author: comment.author,
        max_rshares: max_rshares
      }
    end.reject(&:nil?)
    
    render_discussions(:trending_by_rshares)
  end
  
  def trending_flagged
    options = {
      with: FindTrendingFlaggedJob, tag: @tag, flagged_by: @flagged_by.split(' ')
    }
    
    @discussions = discussions(options)
    
    respond_to do |format|
      format.html { render 'trending_flagged', layout: action_name != 'card' }
      format.atom { render layout: false }
      format.rss { render layout: false }
      format.text { send_urls('trending_flagged') }
    end
  end

  def trending_ignored
    @discussions = discussions(with: FindTrendingIgnoredJob, tag: @tag)
    
    render_discussions(:trending_ignored)
  end

  def vote_ready
    options = {
      limit: 100
    }

    options[:tag] = @tag if !!@tag
    
    response = api_execute(:get_discussions_by_created, options)
    
    @discussions += response.result.map do |comment|
      next if (author_reputation = to_rep comment.author_reputation) < @min_reputation
      next unless comment.active_votes.size <= @max_votes
      next if (created = Time.parse(comment.created + 'Z')) > @min_age_in_minutes.minutes.ago
      
      comment_tags = JSON[comment.json_metadata]["tags"] rescue []
      exclude_tags = [@exclude_tags.split(' ')].flatten
      next if (comment_tags & exclude_tags).any?
      
      {
        symbol: symbol_value(comment.total_pending_payout_value),
        url: comment.url,
        from: comment.author,
        slug: comment.url.split('@').last,
        timestamp: created,
        votes: comment.active_votes.size,
        title: comment.title,
        content: comment.body,
        author_reputation: author_reputation
      }
    end.reject(&:nil?)
    
    render_discussions(:vote_ready)
  end
  
  def flagwar
    @discussions = discussions(with: FindFlagwarJob, tag: @tag)
    
    render_discussions(:flagwar)
  end
  
  def first_post
    options = {
      with: FindFirstPostJob, tag: @tag, min_reputation: @min_reputation,
      exclude_tags: @exclude_tags
    }
    
    @discussions = discussions(options)
    
    render_discussions(:first_post)
  end
  
  def mentions
    @account_names = params[:account_names]
    @after = (Time.parse(params[:after]) rescue 2.hours.ago).to_date
    @discussions = if !!@account_names
      options = {
        with: FindMentionsJob, account_names: @account_names, after: @after,
        tag: @tag, min_reputation: @min_reputation, exclude_tags: @exclude_tags
      }
      
      discussions(options)
    else
      comments.none
    end
    
    page = params[:page] || 1
    per = @limit.to_i
    @discussions = @discussions.paginate(page: page, per_page: per)
    
    render_discussions(:mentions)
  end
  
  def discussions(options = {})
    job = options.delete(:with)
    tag = options[:tag]
    
    if defined? job.discussions
      if !!job.discussions(tag)
        job.perform_now(options)
      else
        job.perform_later(options)
      end
    
      # this will give us the discussions from lastest request
      job.discussions(tag) || []
    else
      job.perform_now(options)
    end
  end
  
  def render_discussions(type)
    respond_to do |format|
      format.html { render type, layout: action_name != 'card' }
      format.atom { render layout: false }
      format.rss { render layout: false }
      format.text { send_urls(type) }
    end
  end
  
  def send_urls(filename)
    urls = @discussions.map do |discussion|
      "#{site_prefix}#{discussion[:url]}"
    end
    
    send_data urls.join("\n"), filename: "#{filename}.txt", content_type: 'text/plain', disposition: :attachment
  end
  
  def comments
    if steemit?
      SteemApi::Comment
    elsif golos?
      GolosCloud::Comment
    end
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
  TRUE_STRING = 'true'.freeze

  def discussion_title
    title = 'Gamymede - '
    
    title << case TRUE_STRING
    when @other_promoted then 'Promoted by Third Parties'
    when @predicted then 'Predicted to Trend'
    when @trending_by_reputation then 'Reputation on Trending'
    when @trending_by_rshares then 'Rshares on Trending'
    when @trending_flagged then 'Flagged on Trending'
    when @trending_ignored then 'Ignored on Trending'
    when @vote_ready then 'Vote Ready'
    when @flagwar then 'Flag War'
    when @first_post then 'First Post'
    else; 'Untitled'
    end
  end
  
  def discussion_active_class(current_tab, classes = [])
    classes << case [current_tab, TRUE_STRING]
    when [:other_promoted, @other_promoted] then 'active'
    when [:predicted, @predicted] then 'active'
    when [:trending, @trending_by_reputation] then 'active'
    when [:trending, @trending_flagged] then 'active'
    when [:trending, @trending_ignored] then 'active'
    when [:trending, @trending_by_rshares] then 'active'
    when [:vote_ready, @vote_ready] then 'active'
    when [:flagwar, @flagwar] then 'active'
    when [:first_post, @first_post] then 'active'
    end
    
    classes.join(' ').strip
  end
  
  def group_pattern(discussion)
    case TRUE_STRING
    when @other_promoted
      [time_ago_in_words(discussion[:timestamp]), discussion[:from], discussion[:amount]]
    when @predicted
      [time_ago_in_words(discussion[:timestamp]), discussion[:amount]]
    when @trending_by_reputation
      [discussion[:author_reputation]]
    when @trending_by_rshares
      [discussion[:max_rshares]]
    when @trending_flagged
      [discussion[:from].size, discussion[:from]]
    when @trending_ignored
      [discussion[:from].size, discussion[:from]]
    when @vote_ready
      [time_ago_in_words(discussion[:timestamp]), discussion[:votes]]
    when @flagwar
      [time_ago_in_words(discussion[:timestamp]), discussion[:upvotes], discussion[:downvotes]]
    when @first_post
      [time_ago_in_words(discussion[:timestamp])]
    else
      [time_ago_in_words(discussion[:timestamp]), discussion[:amount]]
    end
  end
  
  def tags_for_select(selected = '')
    options_for_select tags, selected
  end
  
  def discussion_amounts_total
    totals = {}
    
    @discussions.each do |d|
      a, s = d[:amount].split(' ')
      totals[s] ||= 0
      totals[s] += a.to_f
    end
    
    return 0 if totals.none?
    
    totals.map do |total|
      "%.3f #{total.first}" % total.last
    end.join(", ")
  end
end

app/views/discussions/first_post.html.haml
= content_for :head, auto_discovery_link_tag(:atom, discussions_url(first_post: 'true', min_reputation: @min_reputation, tag: @tag, exclude_tags: @exclude_tags, format: :atom))
= content_for :head, auto_discovery_link_tag(:rss, discussions_url(first_post: 'true', min_reputation: @min_reputation, tag: @tag, exclude_tags: @exclude_tags, format: :rss))

= render partial: 'nav' unless action_name == 'card'

.card.border-top-0{style: 'padding-top: 0'}
  .card-block
    .row
      .col-md-12

        %div.float-right
          = form_tag discussions_path, method: :get, class: 'form-inline' do
            = hidden_field_tag :first_post, true
            .row
              .form-group
                %label{for: :min_reputation} Minimum Reputation:
                = number_field_tag :min_reputation, @min_reputation, class: 'form-control form-control-sm', style: 'width: 48px'
                &nbsp;&nbsp;&nbsp;
              .form-group
                %label{for: :tag} Tag:
                = select_tag :tag, tags_for_select(@tag), class: 'form-control form-control-sm'
                = submit_tag 'Query', class: 'btn btn-primary'

        %br
        %br

        .jumbotron
          %h4 First posts written by the author.

        %small
          %ul
            - @discussions.group_by{ |d| group_pattern(d) }.sort_by{ |d| d.last.last[:timestamp] }.each do |group|
              - key = group.first
              - duration = key.first
              - discussion = group.last.last
              - author = discussion[:slug].split('/').first
              %li
                posted #{duration} ago
                - if group.last.size == 1
                  \-
                  = link_to discussion[:title], "#{site_prefix}#{discussion[:url]}"
                  by
                  = link_to discussion[:from], "#{site_prefix}/@#{discussion[:from]}"
                  %font.reputation= discussion[:author_reputation]
                - else
                  %ul
                    - group.last.each do |discussion|
                      %li
                        = link_to discussion[:title], "#{site_prefix}#{discussion[:url]}"
                        by
                        = link_to discussion[:from], "#{site_prefix}/@#{discussion[:from]}"
                        %font.reputation= discussion[:author_reputation]

        -# See:
        -# =link_to 'How to Find First Posts with Ruby', ''

app/views/discussions/flagwar.html.haml
= content_for :head, auto_discovery_link_tag(:atom, discussions_url(flagwar: 'true', min_reputation: @min_reputation, format: :atom))
= content_for :head, auto_discovery_link_tag(:rss, discussions_url(flagwar: 'true', min_reputation: @min_reputation, format: :rss))

= render partial: 'nav' unless action_name == 'card'

.card.border-top-0{style: 'padding-top: 0'}
  .card-block
    .row
      .col-md-12

        %div.float-right
          = form_tag discussions_path, method: :get do
            = hidden_field_tag :flagwar, true
            Tag:
            = select_tag :tag, tags_for_select(@tag)
            = submit_tag 'Query', class: 'btn btn-primary'

        %br
        %br

        .jumbotron
          %h4 These posts are having a flag war and getting close to cashout time.  Only posts that have top level comments by the downvoter are considered.

        %small
          %ul
            - @discussions.group_by{ |d| group_pattern(d) }.sort_by{ |d| d.last.last[:timestamp] }.each do |group|
              - key = group.first
              - duration = key.first
              - discussion = group.last.last
              - upvotes = discussion[:upvotes]
              - downvotes = discussion[:downvotes]
              - unvotes = discussion[:unvotes]
              - author = discussion[:slug].split('/').first
              - amount = discussion[:amount]
              - symbol = discussion[:symbol]
              %li
                posted #{duration} ago (votes: up: #{upvotes}; down: #{downvotes}), potantal payout: #{amount} #{symbol}
                - if group.last.size == 1
                  \-
                  = link_to discussion[:title], "#{site_prefix}#{discussion[:url]}"
                  by
                  = link_to discussion[:from], "#{site_prefix}/@#{discussion[:from]}"
                  %font.reputation= discussion[:author_reputation]
                - else
                  %ul
                    - group.last.each do |discussion|
                      %li
                        = link_to discussion[:title], "#{site_prefix}#{discussion[:url]}"
                        by
                        = link_to discussion[:from], "#{site_prefix}/@#{discussion[:from]}"
                        %font.reputation= discussion[:author_reputation]

        See:
        =link_to 'How to Find Flagwars with Ruby', 'https://steemit.com/radiator/@inertia/how-to-find-flag-wars-with-ruby'

app/views/discussions/mentions.haml
= content_for :head, auto_discovery_link_tag(:atom, discussions_url(mentions: 'true', min_reputation: @min_reputation, tag: @tag, exclude_tags: @exclude_tags, format: :atom))
= content_for :head, auto_discovery_link_tag(:rss, discussions_url(mentions: 'true', min_reputation: @min_reputation, tag: @tag, exclude_tags: @exclude_tags, format: :rss))

= render partial: 'nav' unless action_name == 'card'

.card.border-top-0{style: 'padding-top: 0'}
  .card-block
    .row
      .col-md-12

        %div.float-right
          = form_tag discussions_path, method: :get, class: 'form-inline' do
            = hidden_field_tag :mentions, true
            .row
              .form-group
                %label{for: :account_names} Account Names:
                = text_field_tag :account_names, @account_names, class: 'form-control form-control-sm', style: 'width: 240px'
                &nbsp;&nbsp;&nbsp;
              .form-group
                %label{for: :after} After:
                = text_field_tag :after, @after, class: 'form-control form-control-sm', style: 'width: 96px'
                &nbsp;&nbsp;&nbsp;
              .form-group
                %label{for: :limit} Limit:
                = number_field_tag :limit, @limit, class: 'form-control form-control-sm', style: 'width: 96px'
                &nbsp;&nbsp;&nbsp;
              .form-group
                %label{for: :min_reputation} Minimum Reputation:
                = number_field_tag :min_reputation, @min_reputation, class: 'form-control form-control-sm', style: 'width: 48px'
                &nbsp;&nbsp;&nbsp;
              -# .form-group
              -#   %label{for: :tag} Tag:
              -#   = select_tag :tag, tags_for_select(@tag), class: 'form-control form-control-sm'
              = submit_tag 'Query', class: 'btn btn-primary'

        %br
        %br

        .jumbotron
          %h4 Mentions of author names.

        %small
          %ul
            -# Save transfer time by only selecting the columns we need.
            - cols = %w(parent_author parent_permlink title permlink author author_reputation)
            - @discussions.select(cols).each do |discussion|
              %li
                - if discussion[:parent_author] == ''
                  - url = "#{site_prefix}/#{discussion[:parent_permlink]}/@#{discussion[:author]}/#{discussion[:permlink]}"
                  = link_to discussion[:title], url
                - else
                  - url = "#{site_prefix}/#{discussion[:parent_permlink]}/@#{discussion[:author]}/#{discussion[:permlink]}"
                  = link_to 'Comment', url
                by
                = link_to discussion[:author], "#{site_prefix}/@#{discussion[:author]}"
                %font.reputation= to_rep discussion[:author_reputation]
                  
        = will_paginate @discussions.select(:id), :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'pagination-lg'

app/views/discussions/other_promoted.html.haml
= content_for :head, auto_discovery_link_tag(:atom, discussions_url(other_promoted: 'true', min_promotion_amount: @min_promotion_amount, format: :atom))
= content_for :head, auto_discovery_link_tag(:rss, discussions_url(other_promoted: 'true', min_promotion_amount: @min_promotion_amount, format: :rss))

= render partial: 'nav' unless action_name == 'card'

.card.border-top-0{style: 'padding-top: 0'}
  .card-block
    .row
      .col-md-12

        %div.float-right
          = form_tag discussions_path, method: :get, class: 'form-inline' do
            = hidden_field_tag :other_promoted, true
            .row
              .form-group
                %label{for: :min_promotion_amount} Minimum Amount:
                = number_field_tag :min_promotion_amount, @min_promotion_amount, class: 'form-control form-control-sm', style: 'width: 96px'
                &nbsp;&nbsp;&nbsp;
              .form-group
                = submit_tag 'Query', class: 'btn btn-primary'

        %br
        %br

        .jumbotron
          %h4
            These posts have been promoted by someone other than the author &hellip; totalling:
            = discussion_amounts_total
              
        %small
          %ul
            - @discussions.group_by{ |d| group_pattern(d) }.sort_by{ |d| d.last.last[:timestamp] }.each do |group|
              - key = group.first
              - duration = key.first
              - from = key.second
              - amount = key.last
              - discussion = group.last.last
              - title = discussion[:slug].split('/')[1..-1].join(' ')
              - title = title.titleize
              %li
                #{duration} ago, #{link_to from, "#{site_prefix}/@#{from}"}
                %font.reputation= discussion[:from_reputation]
                paid #{amount}
                - if group.last.size == 1
                  \-
                  = link_to title, "#{site_prefix}#{discussion[:url]}"
                  by
                  = link_to discussion[:author], "#{site_prefix}/@#{discussion[:author]}"
                  %font.reputation= discussion[:author_reputation]
                - else
                  %ul
                    - group.last.each do |discussion|
                      %li
                        = link_to title, "#{site_prefix}#{discussion[:url]}"
                        by
                        = link_to discussion[:author], "#{site_prefix}/@#{discussion[:author]}"
                        %font.reputation= discussion[:author_reputation]

        See:
        = link_to "How to Find Post Promotions Paid by a Third Party in Ruby", "https://steemit.com/radiator/@inertia/how-to-find-post-promotions-paid-by-a-third-party-in-ruby"

app/views/discussions/predicted.html.haml
= content_for :head, auto_discovery_link_tag(:atom, discussions_url(predicted: 'true', format: :atom))
= content_for :head, auto_discovery_link_tag(:rss, discussions_url(predicted: 'true', format: :rss))

= render partial: 'nav' unless action_name == 'card'

.card.border-top-0{style: 'padding-top: 0'}
  .card-block
    .row
      .col-md-12

        %div.float-right
          = form_tag discussions_path, method: :get do
            = hidden_field_tag :predicted, true
            Tag:
            = select_tag 'tag', tags_for_select(@tag)
            = submit_tag 'Query', class: 'btn btn-primary'

        %br
        %br

        .jumbotron
          %h4
            - if @discussions.any?
              This is a list of new posts and their predicted payout based on
              analysis of the current trending#{!!@tag ? "/#{@tag}" : ''} posts
              &hellip;
            - else
              Unable to do predictions right now.  This might be because there
              were no posts trending for this tag or no new posts to make a
              prediction on.

        %small
          %ul
            - @discussions.group_by{ |d| group_pattern(d) }.sort_by{ |d| d.last.last[:timestamp] }.reverse.each do |group|
              - key = group.first
              - duration = key.first
              - from = key.second
              - amount = key.last
              - discussion = group.last.last
              %li
                #{duration} from now, will rise by: #{amount} #{discussion[:symbol]}
                - if group.last.size == 1
                  \-
                  = link_to discussion[:title], "#{site_prefix}#{discussion[:url]}"
                  by
                  = link_to discussion[:author], "#{site_prefix}/@#{discussion[:author]}"
                  %font.reputation= discussion[:author_reputation]
                - else
                  %ul
                    - group.last.each do |discussion|
                      %li
                        = link_to discussion[:title], "#{site_prefix}#{discussion[:url]}"
                        by
                        = link_to discussion[:author], "#{site_prefix}/@#{discussion[:author]}"
                        %font.reputation= discussion[:author_reputation]

        See:
        = link_to "How to Use AI to Find Articles with Ruby", "https://steemit.com/radiator/@inertia/how-to-use-ai-to-find-articles-with-ruby"

app/views/discussions/trending_by_reputation.html.haml
= content_for :head, auto_discovery_link_tag(:atom, discussions_url(trending_by_reputation: 'true', min_reputation: @min_reputation, max_reputation: @max_reputation, format: :atom))
= content_for :head, auto_discovery_link_tag(:rss, discussions_url(trending_by_reputation: 'true', min_reputation: @min_reputation, max_reputation: @max_reputation, format: :rss))

= render partial: 'nav' unless action_name == 'card'

.card.border-top-0{style: 'padding-top: 0'}
  .card-block
    .row
      .col-md-12

        %div.float-right
          = form_tag discussions_path, method: :get, class: 'form-inline' do
            = hidden_field_tag :trending_by_reputation, true
            .row
              .form-group
                %label{for: :min_reputation} Minimum Reputation:
                = number_field_tag :min_reputation, @min_reputation, class: 'form-control form-control-sm', style: 'width: 48px'
                &nbsp;&nbsp;&nbsp;
              .form-group
                %label{for: :max_reputation} Maximum Reputation:
                = number_field_tag :max_reputation, @max_reputation, class: 'form-control form-control-sm', style: 'width: 48px'
                &nbsp;&nbsp;&nbsp;
              .form-group
                = submit_tag 'Query', class: 'btn btn-primary'
        %br
        %br

        .jumbotron
          %h4
            Trending authors with a minimum reputation of
            %font.reputation= @min_reputation
            and max reputation of
            %font.reputation= @max_reputation
            &hellip;

        %small
          %ul
            - @discussions.group_by{ |d| group_pattern(d) }.sort_by{ |d| d.first }.reverse.each do |group|
              - key = group.first
              - reputation = key.last
              - discussion = group.last.last
              %li
                reputation
                %font.reputation= discussion[:author_reputation]
                - if group.last.size == 1
                  \-
                  = link_to discussion[:title], "#{site_prefix}#{discussion[:url]}"
                  by
                  = link_to discussion[:author], "#{site_prefix}/@#{discussion[:author]}"
                - else
                  %ul
                    - group.last.each do |discussion|
                      %li
                        = link_to discussion[:title], "#{site_prefix}#{discussion[:url]}"
                        by
                        = link_to discussion[:author], "#{site_prefix}/@#{discussion[:author]}"

app/views/discussions/trending_by_rshares.html.haml
= content_for :head, auto_discovery_link_tag(:atom, discussions_url(trending_by_rshares: 'true', min_rshares: @min_rshares, max_rshares: @max_rshares, format: :atom))
= content_for :head, auto_discovery_link_tag(:rss, discussions_url(trending_by_rshares: 'true', min_rshares: @min_rshares, max_rshares: @max_rshares, format: :rss))

= render partial: 'nav' unless action_name == 'card'

.card.border-top-0{style: 'padding-top: 0'}
  .card-block
    .row
      .col-md-12

        %div.float-right
          = form_tag discussions_path, method: :get, class: 'form-inline' do
            = hidden_field_tag :trending_by_rshares, true
            .row
              .form-group
                %label{for: :min_rshares} Minimum Rshares:
                = number_field_tag :min_rshares, @min_rshares, class: 'form-control form-control-sm', style: 'width: 240px'
                &nbsp;&nbsp;&nbsp;
              .form-group
                %label{for: :max_rshares} Maximum Rshares:
                = number_field_tag :max_rshares, @max_rshares, class: 'form-control form-control-sm', style: 'width: 240px'
                &nbsp;&nbsp;&nbsp;
              .form-group
                = submit_tag 'Query', class: 'btn btn-primary'
        %br
        %br

        .jumbotron
          %h4
            Trending authors with a minimum voter rshares of
            %font.rshares= @min_rshares
            and max voter rshares of
            %font.rshares= @max_rshares
            &hellip;

        %small
          %ul
            - @discussions.group_by{ |d| group_pattern(d) }.sort_by{ |d| d.first }.reverse.each do |group|
              - key = group.first
              - rshares = key.last
              - discussion = group.last.last
              %li
                rshares
                %font.rshares= discussion[:max_rshares]
                - if group.last.size == 1
                  \-
                  = link_to discussion[:title], "#{site_prefix}#{discussion[:url]}"
                  by
                  = link_to discussion[:author], "#{site_prefix}/@#{discussion[:author]}"
                - else
                  %ul
                    - group.last.each do |discussion|
                      %li
                        = link_to discussion[:title], "#{site_prefix}#{discussion[:url]}"
                        by
                        = link_to discussion[:author], "#{site_prefix}/@#{discussion[:author]}"