config/routes.rb
Rails.application.routes.draw do
  root to: 'static#index'
  get :favicon, to: 'static#favicon'
  get :mvests, to: 'static#mvests'

  resources :static, only: :index
  resources :discussions, only: :index do
    collection do
      get :card
    end
  end
  resources :blocks, only: :index
  resources :follows, only: :index
  resources :accounts, only: :index
  resources :transfers, only: :index
  resources :tickers, param: :pair, only: [:index, :show]
  resources :charts, param: :account_name, only: [:index, :show] do
    member do
      get :net_transfers
      get :day_of_the_week
    end
  end

  get 'chart/accounts_created', to: 'charts#accounts_created'
  get 'chart/accounts_last_bandwidth_updated', to: 'charts#accounts_last_bandwidth_updated'
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def index
  end

  def net_transfers
    @compare_to = params[:compare_to]
    @account_name = params[:account_name]
    @days = (params[:days] || '14.0').to_f
    @symbol = params[:symbol] || default_debt_asset
    @segments = params[:segments] || 'default'
    @average = 0

    if @days < 2 && @segments == 'default'
      @segments = 'hourly'
    end

    @net_transfers = build_net_transfers(@account_name, @symbol, @days, @segments)
    @days = [@net_transfers.size, @days].min unless @segments == 'hourly'
    @average = if @days == 0
      0
    elsif @segments == 'hourly'
      @net_transfers.map{ |k, v| v }.sum / (@days * 24)
    else
      @net_transfers.map{ |k, v| v }.sum / @days
    end

    if @compare_to.present?
      @compare_to_net_transfers = build_net_transfers(@compare_to, @symbol, @days, @segments)
      @compare_to_average = if @days == 0
        0
      elsif @segments == 'hourly'
        @compare_to_net_transfers.map{ |k, v| v }.sum / (@days * 24)
      else
        @compare_to_net_transfers.map{ |k, v| v }.sum / @days
      end
    end

    @composite = [
      {name: @account_name, data: @net_transfers},
      {name: @compare_to, data: @compare_to_net_transfers}
    ]
  end

  def day_of_the_week
    @compare_to = params[:compare_to]
    @account_name = params[:account_name]
    @days = (params[:days] || '14.0').to_f
    @symbol = params[:symbol] || default_debt_asset

    @net_transfers = build_day_of_the_week(@account_name, @symbol, @days)

    if @compare_to.present?
      @compare_to_net_transfers = build_day_of_the_week(@compare_to, @symbol, @days)
    end

    @composite = [
      {name: @account_name, data: @net_transfers},
      {name: @compare_to, data: @compare_to_net_transfers}
    ]
  end

  def accounts_created
    @days = (params[:days] || '14.0').to_f
    @segments = params[:segments] || 'default'
    @average = 0
    @style = params[:style] || 'default'

    if @days < 2 && @segments == 'default'
      @segments = 'hourly'
    end

    @account_creates = account_creates.where('timestamp > ?', @days.day.ago)
    @account_creates = if @segments == 'hourly'
      @account_creates.group("FORMAT(timestamp, 'HH')").order('format_timestamp_hh')
    else
      @account_creates.group('CAST(timestamp AS DATE)').order('cast_timestamp_as_date')
    end
    @account_creates = @account_creates.count(:all)
    @days = @account_creates.size - 1 unless @segments == 'hourly'
    @total = @account_creates.values.sum
    @average = @total / @days

    case @style
    when 'cumlative'
      total = 0
      @account_creates.each do |k, v|
        @account_creates[k] = (total += v)
      end
    end
  end

  def accounts_last_bandwidth_updated
    @days = (params[:days] || '14.0').to_f
    @segments = params[:segments] || 'default'
    @average = 0
    @style = params[:style] || 'default'

    if @days < 2 && @segments == 'default'
      @segments = 'hourly'
    end

    @account_last_bandwidth_updates = accounts.where('last_bandwidth_update > ?', @days.day.ago)
    @account_last_bandwidth_updates = if @segments == 'hourly'
      @account_last_bandwidth_updates.group("FORMAT(last_bandwidth_update, 'HH')").order('format_last_bandwidth_update_hh')
    else
      @account_last_bandwidth_updates.group('CAST(last_bandwidth_update AS DATE)').order('cast_last_bandwidth_update_as_date')
    end
    @account_last_bandwidth_updates = @account_last_bandwidth_updates.count(:all)
    @days = @account_last_bandwidth_updates.size - 1 unless @segments == 'hourly'
    @total = @account_last_bandwidth_updates.values.sum
    @average = @total / @days

    case @style
    when 'cumlative'
      total = 0
      @account_last_bandwidth_updates.each do |k, v|
        @account_last_bandwidth_updates[k] = (total += v)
      end
    end
  end
private
  def build_net_transfers(account_name, symbol, days, segments)
    bids = transfers.where(to: account_name, amount_symbol: symbol)
    bids = bids.where('timestamp > ?', days.day.ago)
    bids = bids.where('memo LIKE ?', '%@%')
    bids = bids.group_by do |b|
      if segments == 'hourly'
        b.timestamp.strftime("%H")
      else
        b.timestamp.to_date.to_s(:db)
      end
    end

    refunds = transfers.where(from: account_name, amount_symbol: symbol)
    refunds = refunds.where('timestamp > ?', days.day.ago)
    refunds = refunds.where('memo LIKE ?', '%ID:%')
    refunds = refunds.group_by do |b|
      if segments == 'hourly'
        b.timestamp.strftime("%H")
      else
        b.timestamp.to_date.to_s(:db)
      end
    end

    bids.sort_by{ |k, v| k }.map do |k, v|
      refund_sum = [refunds[k]].flatten.compact.map(&:amount).sum
      [k, v.map(&:amount).sum - refund_sum]
    end
  end

  def build_day_of_the_week(account_name, symbol, days)
    bids = transfers.where(to: account_name, amount_symbol: symbol)
    bids = bids.where('timestamp > ?', days.day.ago)
    bids = bids.where('memo LIKE ?', '%@%')
    bids = bids.group_by do |b|
      b.timestamp.strftime('%w %A')
    end

    refunds = transfers.where(from: account_name, amount_symbol: symbol)
    refunds = refunds.where('timestamp > ?', days.day.ago)
    refunds = refunds.where('memo LIKE ?', '%ID:%')
    refunds = refunds.group_by do |b|
      b.timestamp.strftime('%w %A')
    end

    bids.sort_by{ |k, v| k }.map do |k, v|
      refund_sum = [refunds[k]].flatten.compact.map(&:amount).sum
      [k.split(' ').last, v.map(&:amount).sum - refund_sum]
    end

  end

  def default_debt_asset
    if steemit?
      'SBD'
    elsif golos?
      'GBG'
    end
  end

  def transfers
    if steemit?
      SteemApi::Tx::Transfer
    elsif golos?
      GolosCloud::Tx::Transfer
    end
  end

  def account_creates
    if steemit?
      SteemApi::Tx::AccountCreate
    elsif golos?
      GolosCloud::Tx::AccountCreate
    end
  end

  def accounts
    if steemit?
      SteemApi::Account
    elsif golos?
      GolosCloud::Account
    end
  end
end

app/views/charts/accounts_created.html.haml
.card.border-top-0{style: 'padding-top: 0'}
  .card-block
    .row
      .col-md-12

        %div.float-right
          .row
            .col-sm-12
              = form_tag chart_accounts_created_path, method: :get, class: 'form-inline' do
                .form-group
                  %label{for: :days} Days:
                  = number_field_tag :days, @days, class: 'form-control form-control-sm', style: 'width: 64px'
                  &nbsp;&nbsp;&nbsp;
                .form-group
                  %label{for: :segments} Segments:
                  = select_tag :segments, options_for_select([['Default', 'default'], ['Hourly', 'hourly']], @segments)
                  &nbsp;&nbsp;&nbsp;
                .form-group
                  %label{for: :style} Style:
                  = select_tag :style, options_for_select([['Default', 'default'], ['Cumlative', 'cumlative']], @style)
                  = submit_tag 'Draw', class: 'btn btn-primary'
        
        %h1
          Accounts Created
          = surround '(', ')' do
            = pluralize(@days, 'Day')

        - if @style == 'cumlative'
          = area_chart @account_creates
        - else
          = line_chart @account_creates

        %small
          Total:
          = @total
          - unless @segments == 'hourly'
            \|
            Average:
            = @average
            per day

app/views/charts/accounts_last_bandwidth_updated.html.haml
.card.border-top-0{style: 'padding-top: 0'}
  .card-block
    .row
      .col-md-12

        %div.float-right
          .row
            .col-sm-12
              = form_tag chart_accounts_last_bandwidth_updated_path, method: :get, class: 'form-inline' do
                .form-group
                  %label{for: :days} Days:
                  = number_field_tag :days, @days, class: 'form-control form-control-sm', style: 'width: 64px'
                  &nbsp;&nbsp;&nbsp;
                .form-group
                  %label{for: :segments} Segments:
                  = select_tag :segments, options_for_select([['Default', 'default'], ['Hourly', 'hourly']], @segments)
                  &nbsp;&nbsp;&nbsp;
                .form-group
                  %label{for: :style} Style:
                  = select_tag :style, options_for_select([['Default', 'default'], ['Cumlative', 'cumlative']], @style)
                  = submit_tag 'Draw', class: 'btn btn-primary'

        %h1
          Accounts Last Bandwidth Updated
          = surround '(', ')' do
            = pluralize(@days, 'Day')

        - if @style == 'cumlative'
          = area_chart @account_last_bandwidth_updates
        - else
          = line_chart @account_last_bandwidth_updates

        %small
          Total:
          = @total
          - unless @segments == 'hourly'
            \|
            Average:
            = @average
            per day

app/views/charts/day_of_the_week.html.haml
.card.border-top-0{style: 'padding-top: 0'}
  .card-block
    .row
      .col-md-12

        %div.float-right
          .row
            .col-sm-12
              = form_tag day_of_the_week_chart_path(@account_name), method: :get, class: 'form-inline' do
                .form-group
                  %label{for: :symbol} Symbol:
                  = text_field_tag :symbol, @symbol, class: 'form-control form-control-sm', style: 'width: 48px'
                  &nbsp;&nbsp;&nbsp;
                .form-group
                  %label{for: :days} Days:
                  = number_field_tag :days, @days, class: 'form-control form-control-sm', style: 'width: 48px'
                  &nbsp;&nbsp;&nbsp;
                .form-group
                  %label{for: :compare_to} Compare to:
                  = text_field_tag :compare_to, @compare_to, class: 'form-control form-control-sm', style: 'width: 128px'
                  &nbsp;&nbsp;&nbsp;
                  = submit_tag 'Draw', class: 'btn btn-primary'
        
        %h1
          Day of the Week for
          = link_to "@#{@account_name}", "#{site_prefix}/@#{@account_name}"
          = surround '(', ')' do
            = pluralize(@days, 'Day')

        - if @compare_to.present?
          = column_chart @composite
        - else
          = column_chart @net_transfers

app/views/charts/net_transfers.html.haml
.card.border-top-0{style: 'padding-top: 0'}
  .card-block
    .row
      .col-md-12

        %div.float-right
          .row
            .col-sm-12
              = form_tag net_transfers_chart_path(@account_name), method: :get, class: 'form-inline' do
                .form-group
                  %label{for: :symbol} Symbol:
                  = text_field_tag :symbol, @symbol, class: 'form-control form-control-sm', style: 'width: 48px'
                  &nbsp;&nbsp;&nbsp;
                .form-group
                  %label{for: :days} Days:
                  = number_field_tag :days, @days, class: 'form-control form-control-sm', style: 'width: 64px'
                  &nbsp;&nbsp;&nbsp;
                .form-group
                  %label{for: :compare_to} Compare to:
                  = text_field_tag :compare_to, @compare_to, class: 'form-control form-control-sm', style: 'width: 128px'
                  &nbsp;&nbsp;&nbsp;
                .form-group
                  %label{for: :segments} Segments:
                  = select_tag :segments, options_for_select([['Default', 'default'], ['Hourly', 'hourly']], @segments)
                  = submit_tag 'Draw', class: 'btn btn-primary'
        
        %h1
          Net Transfers to
          = link_to "@#{@account_name}", "#{site_prefix}/@#{@account_name}"
          = surround '(', ')' do
            = pluralize(@days, 'Day')

        - if @compare_to.present?
          = line_chart @composite
        - else
          = line_chart @net_transfers

        %small
          - if @compare_to.present?
            = @segments == 'hourly' ? 'Hourly' : 'Daily'
            = @account_name
            average:
            = '%.3f' % @average
            = @symbol
            %br
            = @segments == 'hourly' ? 'Hourly' : 'Daily'
            = @compare_to
            average:
            = '%.3f' % @compare_to_average
            = @symbol
          - else
            Average:
            = '%.3f' % @average
            = @symbol