config/routes.rb
Rails.application.routes.draw do
  root to: 'static#index'
  get :favicon, to: 'static#favicon'
  get :mvests, to: 'static#mvests'

  resources :static, only: :index
  resources :discussions, only: :index do
    collection do
      get :card
    end
  end
  resources :blocks, only: :index
  resources :follows, only: :index
  resources :accounts, only: :index
  resources :transfers, only: :index
  resources :tickers, param: :pair, only: [:index, :show]
  resources :charts, param: :account_name, only: [:index, :show] do
    member do
      get :net_transfers
      get :day_of_the_week
    end
  end

  get 'chart/accounts_created', to: 'charts#accounts_created'
  get 'chart/accounts_last_bandwidth_updated', to: 'charts#accounts_last_bandwidth_updated'
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  def index
    @account = params[:account].presence || nil
    @transfers = []
    
    if !!@account
      response = api_execute(:get_account_history, @account, 2000, 2000)
      response.result.each do |history|
        next unless history.last.op.first == 'transfer'
        op = history.last.op.last
        
        @transfers << {
          trx_id: history.last.trx_id,
          timestamp: Time.parse(history.last.timestamp + 'Z'),
          from: op.from,
          to: op.to,
          amount: op.amount,
          memo: op.memo
        }
        
        respond_to do |format|
          format.html { }
          format.atom { render layout: false }
          format.rss { render layout: false }
        end
      end
    end
  end
end

app/views/transfers/index.html.haml
- if !!@account
  = content_for :head, auto_discovery_link_tag(:atom, transfers_url(account: @account, format: :atom))
  = content_for :head, auto_discovery_link_tag(:rss, transfers_url(account: @account, format: :rss))

%div.float-right
  = form_tag transfers_path, method: :get do
    = text_field_tag :account, @account, placeholder: 'User Name'
    = submit_tag 'Query', class: 'btn btn-primary'
%br
%hr

  .jumbotron
    %h4 Transfers

- if !!@transfers && @transfers.any?
  %table.table-sm.table-striped.table-bordered
    %thead
      %tr
        %th ID
        %th To
        %th Time
        %th Amount
        %th Memo
    %tbody
      - @transfers.each do |transfer|
        %tr
          %td= transfer[:trx_id]
          %td= link_to transfer[:to], "#{site_prefix}/@#{transfer[:to]}"
          %td
            = time_ago_in_words transfer[:timestamp]
            ago
          %td= transfer[:amount]
          %td= transfer[:memo]